        
- hosts: all
  tasks:
        - name: copy war file
          copy: src=./target/spring-petclinic-2.5.0-SNAPSHOT.jar dest=/home/vagrant
          
        - name: run jar file
          shell: screen -L -m -d java -jar /home/vagrant/spring-petclinic-2.5.0-SNAPSHOT.jar

        - name: wait for application to start
          wait_for: port=8080
      
